use cbindgen;

use std::env;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_language(cbindgen::Language::C)
        .with_header("/* Autogenerated by cbindgen */")
        .include_item("Unit")
        .include_item("EdgeData")
        .include_item("Graph")
        .generate()
        .expect("Unable to generate bindings")
      .write_to_file("search.h");
}