use cbindgen;

use std::env;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_language(cbindgen::Language::C)
        .with_header("/* Autogenerated by cbindgen */")
        .with_include("log.h")
        .include_item("UnitData")
        .include_item("EdgeData")
        .include_item("Graph")
        .exclude_item("sys_log")
        .generate()
        .expect("Unable to generate bindings")
      .write_to_file("Grap.h");
}