/* Autogenerated by cbindgen */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include "log.h"

/**
 * 无向图结构。
 */
typedef struct Graph Graph;

/**
 * 表示图中可附着在节点上的“单元”。
 */
typedef struct Unit {
  /**
   * 单元的唯一标识。
   */
  uintptr_t id;
} Unit;

/**
 * 边数据。
 */
typedef struct EdgeData {
  /**
   * 边的权重。
   */
  float weight;
} EdgeData;

struct Graph *create_graph(void);

void destroy_graph(struct Graph *graph);

void add_edge(struct Graph *graph, uintptr_t from, uintptr_t to, float weight);

void visualize_graph(struct Graph *graph);

extern int sys_log(unsigned int log_type,
                   unsigned int level,
                   const char *file,
                   int line,
                   const char *format,
                   ...);
