/* Autogenerated by cbindgen */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct Graph Graph;

typedef struct Unit {
  uintptr_t id;
} Unit;

typedef struct EdgeData {
  float weight;
} EdgeData;

extern int rust_log_printf(const char *format, ...);

struct Graph *create_graph(void);

void destroy_graph(struct Graph *graph);

void add_edge(struct Graph *graph, uintptr_t from, uintptr_t to, float weight);
